//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCarWeb.AracWebServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Araclar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Araclar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlakaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracModeliField;
        
        private int GerekenEhliyetYasiField;
        
        private int MinimumYasSiniriField;
        
        private int GunlukKmSiniriField;
        
        private int AracKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HavaYastigiField;
        
        private int BagajHacmiField;
        
        private int KoltukSayisiField;
        
        private decimal GunlukKiraBedeliField;
        
        private bool RezervField;
        
        private bool KiradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YakitTipiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VitesTipiField;
        
        private System.DateTime KiralanmaTarihiField;
        
        private System.DateTime KiradanDonusTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AracResmiField;
        
        private int MusteriIdField;
        
        private int SirketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracId {
            get {
                return this.AracIdField;
            }
            set {
                if ((this.AracIdField.Equals(value) != true)) {
                    this.AracIdField = value;
                    this.RaisePropertyChanged("AracId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Plaka {
            get {
                return this.PlakaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlakaField, value) != true)) {
                    this.PlakaField = value;
                    this.RaisePropertyChanged("Plaka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AracAdi {
            get {
                return this.AracAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracAdiField, value) != true)) {
                    this.AracAdiField = value;
                    this.RaisePropertyChanged("AracAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AracModeli {
            get {
                return this.AracModeliField;
            }
            set {
                if ((object.ReferenceEquals(this.AracModeliField, value) != true)) {
                    this.AracModeliField = value;
                    this.RaisePropertyChanged("AracModeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GerekenEhliyetYasi {
            get {
                return this.GerekenEhliyetYasiField;
            }
            set {
                if ((this.GerekenEhliyetYasiField.Equals(value) != true)) {
                    this.GerekenEhliyetYasiField = value;
                    this.RaisePropertyChanged("GerekenEhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MinimumYasSiniri {
            get {
                return this.MinimumYasSiniriField;
            }
            set {
                if ((this.MinimumYasSiniriField.Equals(value) != true)) {
                    this.MinimumYasSiniriField = value;
                    this.RaisePropertyChanged("MinimumYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GunlukKmSiniri {
            get {
                return this.GunlukKmSiniriField;
            }
            set {
                if ((this.GunlukKmSiniriField.Equals(value) != true)) {
                    this.GunlukKmSiniriField = value;
                    this.RaisePropertyChanged("GunlukKmSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int AracKm {
            get {
                return this.AracKmField;
            }
            set {
                if ((this.AracKmField.Equals(value) != true)) {
                    this.AracKmField = value;
                    this.RaisePropertyChanged("AracKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string HavaYastigi {
            get {
                return this.HavaYastigiField;
            }
            set {
                if ((object.ReferenceEquals(this.HavaYastigiField, value) != true)) {
                    this.HavaYastigiField = value;
                    this.RaisePropertyChanged("HavaYastigi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal GunlukKiraBedeli {
            get {
                return this.GunlukKiraBedeliField;
            }
            set {
                if ((this.GunlukKiraBedeliField.Equals(value) != true)) {
                    this.GunlukKiraBedeliField = value;
                    this.RaisePropertyChanged("GunlukKiraBedeli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool Rezerv {
            get {
                return this.RezervField;
            }
            set {
                if ((this.RezervField.Equals(value) != true)) {
                    this.RezervField = value;
                    this.RaisePropertyChanged("Rezerv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool Kirada {
            get {
                return this.KiradaField;
            }
            set {
                if ((this.KiradaField.Equals(value) != true)) {
                    this.KiradaField = value;
                    this.RaisePropertyChanged("Kirada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string YakitTipi {
            get {
                return this.YakitTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.YakitTipiField, value) != true)) {
                    this.YakitTipiField = value;
                    this.RaisePropertyChanged("YakitTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string VitesTipi {
            get {
                return this.VitesTipiField;
            }
            set {
                if ((object.ReferenceEquals(this.VitesTipiField, value) != true)) {
                    this.VitesTipiField = value;
                    this.RaisePropertyChanged("VitesTipi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.DateTime KiralanmaTarihi {
            get {
                return this.KiralanmaTarihiField;
            }
            set {
                if ((this.KiralanmaTarihiField.Equals(value) != true)) {
                    this.KiralanmaTarihiField = value;
                    this.RaisePropertyChanged("KiralanmaTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.DateTime KiradanDonusTarihi {
            get {
                return this.KiradanDonusTarihiField;
            }
            set {
                if ((this.KiradanDonusTarihiField.Equals(value) != true)) {
                    this.KiradanDonusTarihiField = value;
                    this.RaisePropertyChanged("KiradanDonusTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string AracResmi {
            get {
                return this.AracResmiField;
            }
            set {
                if ((object.ReferenceEquals(this.AracResmiField, value) != true)) {
                    this.AracResmiField = value;
                    this.RaisePropertyChanged("AracResmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int MusteriId {
            get {
                return this.MusteriIdField;
            }
            set {
                if ((this.MusteriIdField.Equals(value) != true)) {
                    this.MusteriIdField = value;
                    this.RaisePropertyChanged("MusteriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sirket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Sirket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SirketAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        private int AracSayisiField;
        
        private float SirketPuaniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RentaCarWeb.AracWebServis.Yonetici[] YoneticilerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SirketAdi {
            get {
                return this.SirketAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketAdiField, value) != true)) {
                    this.SirketAdiField = value;
                    this.RaisePropertyChanged("SirketAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sehir {
            get {
                return this.SehirField;
            }
            set {
                if ((object.ReferenceEquals(this.SehirField, value) != true)) {
                    this.SehirField = value;
                    this.RaisePropertyChanged("Sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int AracSayisi {
            get {
                return this.AracSayisiField;
            }
            set {
                if ((this.AracSayisiField.Equals(value) != true)) {
                    this.AracSayisiField = value;
                    this.RaisePropertyChanged("AracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public float SirketPuani {
            get {
                return this.SirketPuaniField;
            }
            set {
                if ((this.SirketPuaniField.Equals(value) != true)) {
                    this.SirketPuaniField = value;
                    this.RaisePropertyChanged("SirketPuani");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public RentaCarWeb.AracWebServis.Yonetici[] Yoneticiler {
            get {
                return this.YoneticilerField;
            }
            set {
                if ((object.ReferenceEquals(this.YoneticilerField, value) != true)) {
                    this.YoneticilerField = value;
                    this.RaisePropertyChanged("Yoneticiler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yonetici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Yonetici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcKimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime DogumTarihiField;
        
        private int YoneticiIdField;
        
        private int SirketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcKimlik {
            get {
                return this.TcKimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TcKimlikField, value) != true)) {
                    this.TcKimlikField = value;
                    this.RaisePropertyChanged("TcKimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DogumTarihi {
            get {
                return this.DogumTarihiField;
            }
            set {
                if ((this.DogumTarihiField.Equals(value) != true)) {
                    this.DogumTarihiField = value;
                    this.RaisePropertyChanged("DogumTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int YoneticiId {
            get {
                return this.YoneticiIdField;
            }
            set {
                if ((this.YoneticiIdField.Equals(value) != true)) {
                    this.YoneticiIdField = value;
                    this.RaisePropertyChanged("YoneticiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int SirketId {
            get {
                return this.SirketIdField;
            }
            set {
                if ((this.SirketIdField.Equals(value) != true)) {
                    this.SirketIdField = value;
                    this.RaisePropertyChanged("SirketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracWebServis.AracWebServisSoap")]
    public interface AracWebServisSoap {
        
        // CODEGEN: Generating message contract since element name arac from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracEkle", ReplyAction="*")]
        RentaCarWeb.AracWebServis.AracEkleResponse AracEkle(RentaCarWeb.AracWebServis.AracEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracEkleResponse> AracEkleAsync(RentaCarWeb.AracWebServis.AracEkleRequest request);
        
        // CODEGEN: Generating message contract since element name arac from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracKirala", ReplyAction="*")]
        RentaCarWeb.AracWebServis.AracKiralaResponse AracKirala(RentaCarWeb.AracWebServis.AracKiralaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracKirala", ReplyAction="*")]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracKiralaResponse> AracKiralaAsync(RentaCarWeb.AracWebServis.AracKiralaRequest request);
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracGuncelle", ReplyAction="*")]
        RentaCarWeb.AracWebServis.AracGuncelleResponse AracGuncelle(RentaCarWeb.AracWebServis.AracGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracGuncelleResponse> AracGuncelleAsync(RentaCarWeb.AracWebServis.AracGuncelleRequest request);
        
        // CODEGEN: Generating message contract since element name sirket from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSil", ReplyAction="*")]
        RentaCarWeb.AracWebServis.AracIdSilResponse AracIdSil(RentaCarWeb.AracWebServis.AracIdSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSil", ReplyAction="*")]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracIdSilResponse> AracIdSilAsync(RentaCarWeb.AracWebServis.AracIdSilRequest request);
        
        // CODEGEN: Generating message contract since element name AracHepsiniSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracHepsiniSec", ReplyAction="*")]
        RentaCarWeb.AracWebServis.AracHepsiniSecResponse AracHepsiniSec(RentaCarWeb.AracWebServis.AracHepsiniSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracHepsiniSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracHepsiniSecResponse> AracHepsiniSecAsync(RentaCarWeb.AracWebServis.AracHepsiniSecRequest request);
        
        // CODEGEN: Generating message contract since element name AracIdSecResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSec", ReplyAction="*")]
        RentaCarWeb.AracWebServis.AracIdSecResponse AracIdSec(RentaCarWeb.AracWebServis.AracIdSecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracIdSec", ReplyAction="*")]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracIdSecResponse> AracIdSecAsync(RentaCarWeb.AracWebServis.AracIdSecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracEkle", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracEkleRequestBody Body;
        
        public AracEkleRequest() {
        }
        
        public AracEkleRequest(RentaCarWeb.AracWebServis.AracEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentaCarWeb.AracWebServis.Araclar arac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RentaCarWeb.AracWebServis.Sirket sirket;
        
        public AracEkleRequestBody() {
        }
        
        public AracEkleRequestBody(RentaCarWeb.AracWebServis.Araclar arac, RentaCarWeb.AracWebServis.Sirket sirket) {
            this.arac = arac;
            this.sirket = sirket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracEkleResponseBody Body;
        
        public AracEkleResponse() {
        }
        
        public AracEkleResponse(RentaCarWeb.AracWebServis.AracEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AracEkleResult;
        
        public AracEkleResponseBody() {
        }
        
        public AracEkleResponseBody(bool AracEkleResult) {
            this.AracEkleResult = AracEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracKiralaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracKirala", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracKiralaRequestBody Body;
        
        public AracKiralaRequest() {
        }
        
        public AracKiralaRequest(RentaCarWeb.AracWebServis.AracKiralaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracKiralaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentaCarWeb.AracWebServis.Araclar arac;
        
        public AracKiralaRequestBody() {
        }
        
        public AracKiralaRequestBody(RentaCarWeb.AracWebServis.Araclar arac) {
            this.arac = arac;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracKiralaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracKiralaResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracKiralaResponseBody Body;
        
        public AracKiralaResponse() {
        }
        
        public AracKiralaResponse(RentaCarWeb.AracWebServis.AracKiralaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracKiralaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AracKiralaResult;
        
        public AracKiralaResponseBody() {
        }
        
        public AracKiralaResponseBody(bool AracKiralaResult) {
            this.AracKiralaResult = AracKiralaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracGuncelleRequestBody Body;
        
        public AracGuncelleRequest() {
        }
        
        public AracGuncelleRequest(RentaCarWeb.AracWebServis.AracGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentaCarWeb.AracWebServis.Araclar entity;
        
        public AracGuncelleRequestBody() {
        }
        
        public AracGuncelleRequestBody(RentaCarWeb.AracWebServis.Araclar entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracGuncelleResponseBody Body;
        
        public AracGuncelleResponse() {
        }
        
        public AracGuncelleResponse(RentaCarWeb.AracWebServis.AracGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracGuncelleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AracGuncelleResult;
        
        public AracGuncelleResponseBody() {
        }
        
        public AracGuncelleResponseBody(bool AracGuncelleResult) {
            this.AracGuncelleResult = AracGuncelleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracIdSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracIdSil", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracIdSilRequestBody Body;
        
        public AracIdSilRequest() {
        }
        
        public AracIdSilRequest(RentaCarWeb.AracWebServis.AracIdSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracIdSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RentaCarWeb.AracWebServis.Sirket sirket;
        
        public AracIdSilRequestBody() {
        }
        
        public AracIdSilRequestBody(int id, RentaCarWeb.AracWebServis.Sirket sirket) {
            this.id = id;
            this.sirket = sirket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracIdSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracIdSilResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracIdSilResponseBody Body;
        
        public AracIdSilResponse() {
        }
        
        public AracIdSilResponse(RentaCarWeb.AracWebServis.AracIdSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracIdSilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AracIdSilResult;
        
        public AracIdSilResponseBody() {
        }
        
        public AracIdSilResponseBody(bool AracIdSilResult) {
            this.AracIdSilResult = AracIdSilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracHepsiniSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracHepsiniSec", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracHepsiniSecRequestBody Body;
        
        public AracHepsiniSecRequest() {
        }
        
        public AracHepsiniSecRequest(RentaCarWeb.AracWebServis.AracHepsiniSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AracHepsiniSecRequestBody {
        
        public AracHepsiniSecRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracHepsiniSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracHepsiniSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracHepsiniSecResponseBody Body;
        
        public AracHepsiniSecResponse() {
        }
        
        public AracHepsiniSecResponse(RentaCarWeb.AracWebServis.AracHepsiniSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracHepsiniSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentaCarWeb.AracWebServis.Araclar[] AracHepsiniSecResult;
        
        public AracHepsiniSecResponseBody() {
        }
        
        public AracHepsiniSecResponseBody(RentaCarWeb.AracWebServis.Araclar[] AracHepsiniSecResult) {
            this.AracHepsiniSecResult = AracHepsiniSecResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracIdSecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracIdSec", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracIdSecRequestBody Body;
        
        public AracIdSecRequest() {
        }
        
        public AracIdSecRequest(RentaCarWeb.AracWebServis.AracIdSecRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracIdSecRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public AracIdSecRequestBody() {
        }
        
        public AracIdSecRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracIdSecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracIdSecResponse", Namespace="http://tempuri.org/", Order=0)]
        public RentaCarWeb.AracWebServis.AracIdSecResponseBody Body;
        
        public AracIdSecResponse() {
        }
        
        public AracIdSecResponse(RentaCarWeb.AracWebServis.AracIdSecResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracIdSecResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RentaCarWeb.AracWebServis.Araclar AracIdSecResult;
        
        public AracIdSecResponseBody() {
        }
        
        public AracIdSecResponseBody(RentaCarWeb.AracWebServis.Araclar AracIdSecResult) {
            this.AracIdSecResult = AracIdSecResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracWebServisSoapChannel : RentaCarWeb.AracWebServis.AracWebServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracWebServisSoapClient : System.ServiceModel.ClientBase<RentaCarWeb.AracWebServis.AracWebServisSoap>, RentaCarWeb.AracWebServis.AracWebServisSoap {
        
        public AracWebServisSoapClient() {
        }
        
        public AracWebServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracWebServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracWebServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentaCarWeb.AracWebServis.AracEkleResponse RentaCarWeb.AracWebServis.AracWebServisSoap.AracEkle(RentaCarWeb.AracWebServis.AracEkleRequest request) {
            return base.Channel.AracEkle(request);
        }
        
        public bool AracEkle(RentaCarWeb.AracWebServis.Araclar arac, RentaCarWeb.AracWebServis.Sirket sirket) {
            RentaCarWeb.AracWebServis.AracEkleRequest inValue = new RentaCarWeb.AracWebServis.AracEkleRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracEkleRequestBody();
            inValue.Body.arac = arac;
            inValue.Body.sirket = sirket;
            RentaCarWeb.AracWebServis.AracEkleResponse retVal = ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracEkle(inValue);
            return retVal.Body.AracEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracEkleResponse> RentaCarWeb.AracWebServis.AracWebServisSoap.AracEkleAsync(RentaCarWeb.AracWebServis.AracEkleRequest request) {
            return base.Channel.AracEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracEkleResponse> AracEkleAsync(RentaCarWeb.AracWebServis.Araclar arac, RentaCarWeb.AracWebServis.Sirket sirket) {
            RentaCarWeb.AracWebServis.AracEkleRequest inValue = new RentaCarWeb.AracWebServis.AracEkleRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracEkleRequestBody();
            inValue.Body.arac = arac;
            inValue.Body.sirket = sirket;
            return ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentaCarWeb.AracWebServis.AracKiralaResponse RentaCarWeb.AracWebServis.AracWebServisSoap.AracKirala(RentaCarWeb.AracWebServis.AracKiralaRequest request) {
            return base.Channel.AracKirala(request);
        }
        
        public bool AracKirala(RentaCarWeb.AracWebServis.Araclar arac) {
            RentaCarWeb.AracWebServis.AracKiralaRequest inValue = new RentaCarWeb.AracWebServis.AracKiralaRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracKiralaRequestBody();
            inValue.Body.arac = arac;
            RentaCarWeb.AracWebServis.AracKiralaResponse retVal = ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracKirala(inValue);
            return retVal.Body.AracKiralaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracKiralaResponse> RentaCarWeb.AracWebServis.AracWebServisSoap.AracKiralaAsync(RentaCarWeb.AracWebServis.AracKiralaRequest request) {
            return base.Channel.AracKiralaAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracKiralaResponse> AracKiralaAsync(RentaCarWeb.AracWebServis.Araclar arac) {
            RentaCarWeb.AracWebServis.AracKiralaRequest inValue = new RentaCarWeb.AracWebServis.AracKiralaRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracKiralaRequestBody();
            inValue.Body.arac = arac;
            return ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracKiralaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentaCarWeb.AracWebServis.AracGuncelleResponse RentaCarWeb.AracWebServis.AracWebServisSoap.AracGuncelle(RentaCarWeb.AracWebServis.AracGuncelleRequest request) {
            return base.Channel.AracGuncelle(request);
        }
        
        public bool AracGuncelle(RentaCarWeb.AracWebServis.Araclar entity) {
            RentaCarWeb.AracWebServis.AracGuncelleRequest inValue = new RentaCarWeb.AracWebServis.AracGuncelleRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracGuncelleRequestBody();
            inValue.Body.entity = entity;
            RentaCarWeb.AracWebServis.AracGuncelleResponse retVal = ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracGuncelle(inValue);
            return retVal.Body.AracGuncelleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracGuncelleResponse> RentaCarWeb.AracWebServis.AracWebServisSoap.AracGuncelleAsync(RentaCarWeb.AracWebServis.AracGuncelleRequest request) {
            return base.Channel.AracGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracGuncelleResponse> AracGuncelleAsync(RentaCarWeb.AracWebServis.Araclar entity) {
            RentaCarWeb.AracWebServis.AracGuncelleRequest inValue = new RentaCarWeb.AracWebServis.AracGuncelleRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracGuncelleRequestBody();
            inValue.Body.entity = entity;
            return ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentaCarWeb.AracWebServis.AracIdSilResponse RentaCarWeb.AracWebServis.AracWebServisSoap.AracIdSil(RentaCarWeb.AracWebServis.AracIdSilRequest request) {
            return base.Channel.AracIdSil(request);
        }
        
        public bool AracIdSil(int id, RentaCarWeb.AracWebServis.Sirket sirket) {
            RentaCarWeb.AracWebServis.AracIdSilRequest inValue = new RentaCarWeb.AracWebServis.AracIdSilRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracIdSilRequestBody();
            inValue.Body.id = id;
            inValue.Body.sirket = sirket;
            RentaCarWeb.AracWebServis.AracIdSilResponse retVal = ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracIdSil(inValue);
            return retVal.Body.AracIdSilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracIdSilResponse> RentaCarWeb.AracWebServis.AracWebServisSoap.AracIdSilAsync(RentaCarWeb.AracWebServis.AracIdSilRequest request) {
            return base.Channel.AracIdSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracIdSilResponse> AracIdSilAsync(int id, RentaCarWeb.AracWebServis.Sirket sirket) {
            RentaCarWeb.AracWebServis.AracIdSilRequest inValue = new RentaCarWeb.AracWebServis.AracIdSilRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracIdSilRequestBody();
            inValue.Body.id = id;
            inValue.Body.sirket = sirket;
            return ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracIdSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentaCarWeb.AracWebServis.AracHepsiniSecResponse RentaCarWeb.AracWebServis.AracWebServisSoap.AracHepsiniSec(RentaCarWeb.AracWebServis.AracHepsiniSecRequest request) {
            return base.Channel.AracHepsiniSec(request);
        }
        
        public RentaCarWeb.AracWebServis.Araclar[] AracHepsiniSec() {
            RentaCarWeb.AracWebServis.AracHepsiniSecRequest inValue = new RentaCarWeb.AracWebServis.AracHepsiniSecRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracHepsiniSecRequestBody();
            RentaCarWeb.AracWebServis.AracHepsiniSecResponse retVal = ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracHepsiniSec(inValue);
            return retVal.Body.AracHepsiniSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracHepsiniSecResponse> RentaCarWeb.AracWebServis.AracWebServisSoap.AracHepsiniSecAsync(RentaCarWeb.AracWebServis.AracHepsiniSecRequest request) {
            return base.Channel.AracHepsiniSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracHepsiniSecResponse> AracHepsiniSecAsync() {
            RentaCarWeb.AracWebServis.AracHepsiniSecRequest inValue = new RentaCarWeb.AracWebServis.AracHepsiniSecRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracHepsiniSecRequestBody();
            return ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracHepsiniSecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RentaCarWeb.AracWebServis.AracIdSecResponse RentaCarWeb.AracWebServis.AracWebServisSoap.AracIdSec(RentaCarWeb.AracWebServis.AracIdSecRequest request) {
            return base.Channel.AracIdSec(request);
        }
        
        public RentaCarWeb.AracWebServis.Araclar AracIdSec(int id) {
            RentaCarWeb.AracWebServis.AracIdSecRequest inValue = new RentaCarWeb.AracWebServis.AracIdSecRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracIdSecRequestBody();
            inValue.Body.id = id;
            RentaCarWeb.AracWebServis.AracIdSecResponse retVal = ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracIdSec(inValue);
            return retVal.Body.AracIdSecResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracIdSecResponse> RentaCarWeb.AracWebServis.AracWebServisSoap.AracIdSecAsync(RentaCarWeb.AracWebServis.AracIdSecRequest request) {
            return base.Channel.AracIdSecAsync(request);
        }
        
        public System.Threading.Tasks.Task<RentaCarWeb.AracWebServis.AracIdSecResponse> AracIdSecAsync(int id) {
            RentaCarWeb.AracWebServis.AracIdSecRequest inValue = new RentaCarWeb.AracWebServis.AracIdSecRequest();
            inValue.Body = new RentaCarWeb.AracWebServis.AracIdSecRequestBody();
            inValue.Body.id = id;
            return ((RentaCarWeb.AracWebServis.AracWebServisSoap)(this)).AracIdSecAsync(inValue);
        }
    }
}
